language: python

python:
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install blender
  - pip install pylint
  - pip install pep8

install:
  - wget http://mirror.cs.umn.edu/blender.org/release/Blender2.75/blender-2.75-linux-glibc211-x86_64.tar.bz2
  - tar jxf blender-2.75-linux-glibc211-x86_64.tar.bz2
  - bash tests/install_sample.sh sample blender-2.75-linux-glibc211-x86_64/2.75/scripts/addons
  - cp tests/test_sample.py blender-2.75-linux-glibc211-x86_64
  - ls -al

before_script:
  - cp .pylintrc ~/
  - bash tests/check_sample_code.sh sample
  - cd blender-2.75-linux-glibc211-x86_64

script: ./blender --factory-startup --background -noaudio --python test_sample.py
